### ISSUE TITLE
can't generate tags page properly.

### ISSUE THREAD

**Issue by haichao592** [klugjo/hexo-theme-clean-blog#17]
this theme seems  can't generate tags page properly.
you can visit my site haichao.me to verify.
## and I set tags  index.md like this:

title: tags
date: 2016-06-08 16:19:38
type: tags
## comments: false

and i also checked the public/tags/index.html, there is no tag information.

**Comment by GHLandy** [comment]
Yeah,it can't！I have talking about this problem，it can only generate the tags index, like /tags/linux/index.html。you can edit source/tags/index.md file by yourself.

**Comment by klugjo** [comment]
This is a Hexo limitation, not the theme.

You can try to create a custom page:

source/tag.md

with this header

```
title: Tags
date: 2013-12-26 22:52:56
---
```

and this will create a `/tags.html` page at the root of the site
