### ISSUE TITLE
How do I assign a favicon in clean blog?

### ISSUE THREAD

**Issue by jordancclive** [klugjo/hexo-theme-clean-blog#20]
Sorry if this is a stupid question. Please let me know where the best place would have been for me to find the answer to this question. Thanks so much for an amazing theme!

**Comment by GHLandy** [comment]
You can edit hexo-theme-clean-blog/layout/_partial/head.ejs, add this line 
![image](https://cloud.githubusercontent.com/assets/14830914/17274109/dcfcafa8-5702-11e6-9813-0a1c58534378.png)

anywhere you like.

**Comment by klugjo** [comment]
@jordancclive
this is correct, please edit the layout/_partial/head.ejs to add your favicon like you would with any other HTML file.

Hope that helps
