### ISSUE TITLE
Missing featured images and descriptions when I post my URL or blog posts on social media.

### ISSUE THREAD

**Issue by jordancclive** [klugjo/hexo-theme-clean-blog#21]
I've tried these three with no luck:
- https://github.com/leviwheatcroft/hexo-thumbnails
- https://www.npmjs.com/package/hexo-featured-image
- https://github.com/roybein/hexo-url-image

**Comment by klugjo** [comment]
Can you try to specify a `share_cover` property in the front matter ?

You can check out the open graph implementation here

https://github.com/klugjo/hexo-theme-clean-blog/blob/master/layout/_partial/head.ejs

Do not hesitate if you need more explanations 👍
