### ISSUE TITLE
How can I change the background image in the about page or contact page?

### ISSUE THREAD

**Issue by lchreal6** [klugjo/hexo-theme-clean-blog#22]

**Comment by klugjo** [comment]
By default, posts will use the home page cover image. You can specify a custom cover in the front-matter:

```
title: Excerpts
date: 2013-12-25 00:23:23
tags: ["Excertps"]
cover: /assets/contact-bg.jpg
---
```

**Comment by lchreal6** [comment]
## Can I create the new  tags page and all the tags are in this page?I  add the type of tags in the hexo/source/tags / index.md:

title: tagcloud
date: 2016-08-13 10:05:55

## type: "tags"  

I entered into the tags page but it didn't work.

**Comment by klugjo** [comment]
This tag cloud page is not supported by hexo unfortunately ..

**Comment by lchreal6** [comment]
ok,thanks for your help ,i love your great blog.
