### ISSUE TITLE
can i have tags and categories in the blog?

### ISSUE THREAD

**Issue by weqeo** [klugjo/hexo-theme-clean-blog#23]
I'm tring to create a tags for my blog ,but it's not work...
[This is my blog ](http://weqeo.com/)

**Comment by klugjo** [comment]
Your blog is using a different theme

Tags and Categories are supported by hexo-clean-blog using [the standard way](https://hexo.io/docs/front-matter.html)

**Comment by weqeo** [comment]
@klugjo I just tried other theme two hours ago. But i think i like your theme more.

**Comment by klugjo** [comment]
cool :) 

Let me know if you have some issues displaying categories and tags

**Comment by weqeo** [comment]
I set a tag named "666" in [this article](http://weqeo.com/2016/10/11/Hexo%E4%B8%AD%E6%92%AD%E6%94%BE%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9A%84%E5%AE%9E%E8%B7%B5/),but in the [tag page](http://weqeo.com/tags/) i can't find it.

**Comment by weqeo** [comment]
The categories also not working too.

**Comment by GHLandy** [comment]
The theme won't generate tags index page automatically，you may need to edit it.

**Comment by klugjo** [comment]
GHLandy is correct. You will have to edit the page yourself.

Sorry this is a limitation of hexo, not the theme !

**Comment by klugjo** [comment]
There is now a tags and categories index page.

Demo here:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/

Documentation here:
https://github.com/klugjo/hexo-theme-clean-blog#tags-page
