### ISSUE TITLE
The Archives page's title just display "Archiv"

### ISSUE THREAD

**Issue by 1asso** [klugjo/hexo-theme-clean-blog#28]
Why?

**Comment by GHLandy** [comment]
Can you show your blog link?

**Comment by klugjo** [comment]
Example ?

**Comment by 1asso** [comment]
By the way, how can i add RSS to my blog? Thanks a lot

**Comment by vurihuang** [comment]
Open this file `clean-blog/languages/de.yml`, you can see `archive_a: Archiv`. Maybe you use the `de.yml` language template.
