### ISSUE TITLE
How can I make a excerpt for the article in the home page?

### ISSUE THREAD

**Issue by fox1226** [klugjo/hexo-theme-clean-blog#3]
Hi 
This theme is really beautiful.

I am a beginner of web design
I have spent a whole day but I can't make the excerpt shows in my index

< !--more-- > is useless 

Waiting for your reply
Thank you.

**Comment by klugjo** [comment]
Hi,

This theme does not support traditional excerpts. To show excerpts on the index page, use `subtitle` in the front-matter

i.e

```
title: Excerpts
date: 2013-12-25 00:23:23
tags: ["Excertps"]
subtitle: Standard Excerpts are not supported in Clean Blog but you can use subtitles in the front matter to display text in the index.
---
```

I have updated the documentation. Let me know if that works !
