### ISSUE TITLE
The archives page's title was "Archiv".Is it "Archives"?

### ISSUE THREAD

**Issue by lidudutju** [klugjo/hexo-theme-clean-blog#31]

**Comment by GHLandy** [comment]
设置了站点语言没有，好像默认使用的语言有些问题。

**Comment by klugjo** [comment]
I am not sure how that happened. Can you provide more details ?

If the language is set to english, the title should be `Archives`

**Comment by lidudutju** [comment]
I have set the language to zh-Hans. 
Yes, you are right. When I set to en, title is right indeed!

**Comment by GHLandy** [comment]
You can set the language to zh-CN to display chinese.

**Comment by lidudutju** [comment]
OK, Thanks!
