### ISSUE TITLE
No category and tags.

### ISSUE THREAD

**Issue by jacinzhang** [klugjo/hexo-theme-clean-blog#34]
No category and tags in home menu.

**Comment by klugjo** [comment]
- You can configure the menu yourself if needed
- By default, hexo does not support list of tags and categories type of pages

**Comment by klugjo** [comment]
There is now a tags and categories index page.

Demo here:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/

Documentation here:
https://github.com/klugjo/hexo-theme-clean-blog#tags-page
