### ISSUE TITLE
Tags doesn't show

### ISSUE THREAD

**Issue by qianch3n** [klugjo/hexo-theme-clean-blog#35]
I add the `Tags: /tags` in menu. The directory is correct. But it return 404 error when I click at the tags.

**Comment by klugjo** [comment]
There has been a lot of people asking about this but to my knowlege, Hexo does not support list of tags and categories type of pages

**Comment by klugjo** [comment]
There is now a tags and categories index page.

Demo here:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/

Documentation here:
https://github.com/klugjo/hexo-theme-clean-blog#tags-page
