### ISSUE TITLE
About the tags 

### ISSUE THREAD

**Issue by songtoy** [klugjo/hexo-theme-clean-blog#37]
Excuse me, can somebody tell me how to generate an index for the tags?
I want to have a page that contains all the tags.

**Comment by klugjo** [comment]
I will take care of it, please give me a day or two. cheers

**Comment by klugjo** [comment]
There is now a tags and categories index page.

Demo here:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/

Documentation here:
https://github.com/klugjo/hexo-theme-clean-blog#tags-page

**Comment by songtoy** [comment]
Thanks.That really helps me a lot.
Thank you so much!
