### ISSUE TITLE
这个主题是不是部署有点问题

### ISSUE THREAD

**Issue by chenzengze** [klugjo/hexo-theme-clean-blog#38]
本地适用，远程同步之后就显示有问题。
其他的主题没这个问题。

**Comment by klugjo** [comment]
please use english. My mandarin is very limited

**Comment by chenzengze** [comment]
this topic is not available on my mac book, my localhost works well, but when i push it to github.io, it doesn't work well. but other topic works well

**Comment by klugjo** [comment]
I dont understand. Can you give me more details on the issue you are facing ?
