### ISSUE TITLE
How can I hide some posts at home page

### ISSUE THREAD

**Issue by zydarChen** [klugjo/hexo-theme-clean-blog#39]
Hi, for some reason, I don't want to show some posts at home page, how can I do it?

**Comment by klugjo** [comment]
where do you want to show the posts then ?

**Comment by zydarChen** [comment]
it may be show at Archives or tags/mytag. Because some of the posts for recording something are not ready  to be a article at the home pages.

**Comment by klugjo** [comment]
I don't think this is supported by Hexo. Do you have an example of theme that supports that ?

If you know how to code, you can modify the theme to do that:

in here: https://github.com/klugjo/hexo-theme-clean-blog/blob/master/layout/index.ejs#L21

you need to put a if and check if you want to display or not.

You can check for a property that you will add in the front-matter of your posts

**Comment by zydarChen** [comment]
OK, I will try it. Thank you so much and like your theme very much!
