### ISSUE TITLE
I cannot show table in markdown

### ISSUE THREAD

**Issue by HermioneZhang** [klugjo/hexo-theme-clean-blog#40]
Something is wrong with resolving tables in markdown into html...
I wrote:
```
|bucket 0  |  bucket 1 |
|:---------: | :---------: |
|E F G H I | A B C D   |
```
It just did not show what I expected to become like a table

**Comment by klugjo** [comment]
What is the result ?

You problem might be related to the markdown engine of hexo, not the theme.

Can you provide more details ?

**Comment by HermioneZhang** [comment]
I mean, it shows original markdown text.
It seems like the web cannot resolve this markdown text.
```
|bucket 0  |  bucket 1 |
|:---------: | :---------: |
|E F G H I | A B C D   |
```

**Comment by klugjo** [comment]
Can you try

```
bucket 0 | bucket 1
--- | ---
EFGHI | ABCD
```

**Comment by HermioneZhang** [comment]
I just tried. It didn't work.
It shows as the following:
![image](https://user-images.githubusercontent.com/23000806/28953916-0d58276c-790e-11e7-8e8c-8422057c32fb.png)

**Comment by klugjo** [comment]
I think your problem comes from hexo not this theme.

Can you try with another theme ?

**Comment by HermioneZhang** [comment]
But why a theme called NEXT can resolve tables?

**Comment by klugjo** [comment]
It works for me. Please check this page for an example:

http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/2013/12/24/elements/

![image](https://user-images.githubusercontent.com/2960040/28991564-315056fe-79bc-11e7-83bb-ed3da930fd1c.png)

The corresponding markdown is (copy pasted from my source code)

```
## Table

| Table Header 1 | Table Header 2 | Table Header 3 |
| - | - | - |
| Division 1 | Division 2 | Division 3 |
| Division 1 | Division 2 | Division 3 |
| Division 1 | Division 2 | Division 3 |
```
