### ISSUE TITLE
I can't show my markdown table in my blog

### ISSUE THREAD

**Issue by 234424169** [klugjo/hexo-theme-clean-blog#42]
As the title ,I write a graph in markdown but it can't show right in my blog.
![image](https://user-images.githubusercontent.com/15716467/29951725-26ecc094-8ef7-11e7-80c7-fbece70405d4.png)

This graph can show right in another markdown editor ,can you tell me why?

**Comment by klugjo** [comment]
I think you need to checkout the https://mermaidjs.github.io/ website and see how you can integrate it to this theme. I have no plan of supporting this by default.

It will require some coding though
