### ISSUE TITLE
Where should the favicon file be located?

### ISSUE THREAD

**Issue by podybman** [klugjo/hexo-theme-clean-blog#44]
I've a local fav icon. I've put it in the source/img folder but it doesn't work this way. Where should it be?

Thanks,

**Comment by klugjo** [comment]
You can put it wherever you want as long as you put the right path in the theme's `_config.yml`.

so if your file is in `/img/favicon.ico`, you need to input that path in the config:

```
# set your own favicon
favicon: /img/favicon.ico
```

The value inside the config is used here: https://github.com/klugjo/hexo-theme-clean-blog/blob/master/layout/_partial/head.ejs#L98-L101

that should help you set it up properly
