### ISSUE TITLE
implement search box for this theme.

### ISSUE THREAD

**Issue by varunchandak** [klugjo/hexo-theme-clean-blog#45]
Any tutorial to help implement search box in this would be helpful.

**Comment by klugjo** [comment]
I am not planning on implementing this feature for this theme but feel free to submit a PR if you do. The solution that is generally chosen for Hexo themes is a simple redirect to a domain specific (the current domain) google search.

Checkout Hexo's default theme for an example: https://hexo.io/hexo-theme-landscape/
