### ISSUE TITLE
Tag page

### ISSUE THREAD

**Issue by SquidAnan** [klugjo/hexo-theme-clean-blog#49]
I followed the steps in README and created the tags page
But how can I access the code of the layout of the tag page?
I mean [this page](http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/Tag-1/) ,not [this page](http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/) (I already know how to access the latter)
I can't find anything I want in `themes/clean-blog/layout`
I don't understand how those files are generated under the folder `tags` (for example, `tags/Tag-1`) by reading your code
Is it possible to change the layout? Or is it something done by Hexo?

By the way, thank you for creating this great theme

**Comment by klugjo** [comment]
It is actually the same as archives:

https://github.com/klugjo/hexo-theme-clean-blog/blob/master/layout/archive.ejs

Which is standard for Hexo yes. Most themes work the same way

**Comment by SquidAnan** [comment]
Oh okay I see!
Thanks for replying so soon!!

**Comment by JamesLiuft** [comment]
I really don't know why it not work on my blog = =
