### ISSUE TITLE
Categories Page

### ISSUE THREAD

**Issue by JamesLiuft** [klugjo/hexo-theme-clean-blog#51]
I have created a categories page, but I don't know how to add my categroies on blogs.Could u please give me some solution? Waiting for your apply.Thanks a lot.

**Comment by JamesLiuft** [comment]
opps, maybe i find the deal for this issues.~

**Comment by klugjo** [comment]
If anybody is looking for it, here are the instructions:

https://github.com/klugjo/hexo-theme-clean-blog#categories-page
