### ISSUE TITLE
Question about categories

### ISSUE THREAD

**Issue by joont92** [klugjo/hexo-theme-clean-blog#57]
Hi, thank you for making this theme.  
It's so cool, but I have two question for this.  

### First question
I already configured categories, but it seems like that doesn't support sub directories.  
I have sub directory(category) for my post, like  

```
linux/about-linux.md
linux/ubuntu/about-ubuntu.md
linux/centos/about-centos.md
```

I even have 3-depth category as well.  
It's not supported?  
If it's not supported, I wanna watch some code about this feature.  
Could you tell me where code it is?  

### Second question
After configure categories, I can see that _draft directory also in `categories` pages.  
I don't wanna expose this directroy. Is there any way to do this?  
If it's not support, I'm gonna appreciate you to tell me where code is.  

Thank you.

**Comment by klugjo** [comment]
Hi,

For your first question, the code is here:

https://github.com/klugjo/hexo-theme-clean-blog/blob/master/layout/page.ejs

Have a look at line 10 and see if you can generate your sub categories from there.

And I am not sure I really understand the second question...

**Comment by joont92** [comment]
![image](https://user-images.githubusercontent.com/18513953/48670079-c7ffa400-eb54-11e8-90a9-ae428f6e985e.png)

It looks like the category also contains a _draft folder.
I don't wanna contain it here. Is there any way to do it?

**Comment by klugjo** [comment]
I am not sure why this category shows up ... It might not be related to the theme since nobody seems to have experienced the same issue

**Comment by joont92** [comment]
Hmmmm... okay. I'm gonna check another.  
Thanks for replying.
