### ISSUE TITLE
About Tags and Categories

### ISSUE THREAD

**Issue by GHLandy** [klugjo/hexo-theme-clean-blog#8]
Why this theme can‘t generate the Tags or Category index page? Can you that funtion?

**Comment by klugjo** [comment]
The theme can generate the Tags and Category index pages.

Check out the demo:

Example post: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/2016/03/14/Welcome-to-Clean-Blog/

Click on #Tag1:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/Tag-1/

Click on Category1:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/categories/Category-1/

What is your problem exactly ?

**Comment by klugjo** [comment]
If I go on your site:

http://ghlandy.com/2016/Archlinux_installation/

Click on #ARCHLINUX: (This is a TAG)
http://ghlandy.com/Tags/Archlinux/

Click on LINUX: (This is a Category)
http://ghlandy.com/Categories/Linux/

**Comment by GHLandy** [comment]
I have not descript the problem clearly, maybe. What I want is to generate the site_root/Tags/index.html . Yeah, a Tags cloud, and a Category cloud.

**Comment by klugjo** [comment]
This is not supported by Hexo unfortunately. Can you show me a site that has this functionality ?

**Comment by klugjo** [comment]
Please show me a **Hexo** site that has this functionality

**Comment by GHLandy** [comment]
Just like http://cnfeat.com/tags/, But it is powered by Jekyll.

**Comment by klugjo** [comment]
Yes, you need to ask you question on the Hexo Project. If they add it to Hexo, it will be automatically added to this theme :)

https://github.com/hexojs/hexo

**Comment by GHLandy** [comment]
Ok, thank for your reply。

**Comment by klugjo** [comment]
There is now a tags and categories index page.

Demo here:
http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/tags/

Documentation here:
https://github.com/klugjo/hexo-theme-clean-blog#tags-page
