### ISSUE TITLE
white nav text on white background for wide media

### ISSUE THREAD

**Issue by leviwheatcroft** [klugjo/hexo-theme-clean-blog#9]
You can see what I mean if you zoom out on the demo, once the left and right edge of the cover image can be seen, the nav text expands over the white background on the left and right.

If you use a wide enough cover image you'd probably never notice this.. but I don't think a 1280 or 1024 wide image is such an uncommon use case?

**Comment by GHLandy** [comment]
Is there any way to zoom in or out background images automatically?

**Comment by leviwheatcroft** [comment]
well yeah.. but enlarging images automatically is pretty much always a bad idea because they look terrible.

**Comment by klugjo** [comment]
@leviwheatcroft 

I have chosen a different way to fix it -> by extending the width of the cover image to fill in the whole page. Checkout the latest version.

Let me know if that works for you.

**Comment by leviwheatcroft** [comment]
Nice work, that's great. Your fix is much better than my PR...
